/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.111
 * Generated at: 2025-11-26 07:52:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class select_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>Table Data</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            background: linear-gradient(135deg, #74ebd5 0%, #ACB6E5 100%);\n");
      out.write("            font-family: 'Roboto', sans-serif;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            margin: 0;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("        }\n");
      out.write("        .card {\n");
      out.write("            background: #fff;\n");
      out.write("            padding: 2rem 2.5rem;\n");
      out.write("            border-radius: 16px;\n");
      out.write("            box-shadow: 0 8px 32px rgba(44, 62, 80, 0.15);\n");
      out.write("            text-align: center;\n");
      out.write("            max-width: 800px;\n");
      out.write("            width: 100%;\n");
      out.write("        }\n");
      out.write("        h2 {\n");
      out.write("            margin-bottom: 1.2rem;\n");
      out.write("            color: #2d3e50;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        table {\n");
      out.write("            width: 100%;\n");
      out.write("            border-collapse: collapse;\n");
      out.write("            margin-top: 1.5rem;\n");
      out.write("        }\n");
      out.write("        th, td {\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            border-bottom: 1px solid #e0e0e0;\n");
      out.write("            text-align: left;\n");
      out.write("        }\n");
      out.write("        th {\n");
      out.write("            background: linear-gradient(90deg, #74b9ff 0%, #81ecec 100%);\n");
      out.write("            color: #fff;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("        tr:nth-child(even) {\n");
      out.write("            background: #f7fafd;\n");
      out.write("        }\n");
      out.write("        tr:hover {\n");
      out.write("            background: #e3f2fd;\n");
      out.write("        }\n");
      out.write("        .error {\n");
      out.write("            color: #d63031;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"card\">\n");
      out.write("        <h2>Table Data</h2>\n");
      out.write("        ");

        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/jsp303";
            conn = DriverManager.getConnection(url, "root", "");
            String tablename = request.getParameter("tablename");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM " + tablename);
            ResultSetMetaData rsmd = rs.getMetaData();
            int columnCount = rsmd.getColumnCount();
        
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr>\n");
      out.write("            ");
 for (int i = 1; i <= columnCount; i++) { 
      out.write("\n");
      out.write("                <th>");
      out.print( rsmd.getColumnName(i) );
      out.write("</th>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("            </tr>\n");
      out.write("            ");
 while (rs.next()) { 
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                ");
 for (int i = 1; i <= columnCount; i++) { 
      out.write("\n");
      out.write("                    <td>");
      out.print( rs.getString(i) );
      out.write("</td>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("            </tr>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </table>\n");
      out.write("        ");

        } catch (Exception e) {
        
      out.write("\n");
      out.write("            <div class=\"error\">Error: ");
      out.print( e.getMessage() );
      out.write("</div>\n");
      out.write("        ");

        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
        
      out.write("\n");
      out.write("            <div class=\"error\">Error closing resources: ");
      out.print( e.getMessage() );
      out.write("</div>\n");
      out.write("        ");

            }
        }
        
      out.write("\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
